### ISSUE TITLE
Factory/Service for creating Github web hooks.

### ISSUE THREAD

**Issue by davideast** [jeffbcross/offline-github#3]
This app will need to create web hooks on the fly. This requires an HTTP POST to the Github API. Rather than using ad-hoc `$http.post()` calls, this should be refactored into a service/factory.

**Comment by jeffbcross** [comment]
Good idea, what do you think for the name and API of the service?

**Comment by jeffbcross** [comment]
Oh, nm, I see you've started a branch https://github.com/jeffbcross/offline-github/commit/dc6457c0107b199def76ea0d5649a4615d866aff

**Comment by davideast** [comment]
I called the generic one, `githubHookFactory`. The one specific to the repo is called `captainHook`, because pirates are awesome.
